# Generated by Django 4.2.7 on 2023-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('favorite_color', models.CharField(choices=[('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('BLACK', 'Black'), ('WHITE', 'White'), ('BROWN', 'Brown'), ('BORING', 'None because I am boring')], default='BORING', max_length=20)),
            ],
        ),
    ]
