# Generated by Django 4.2.7 on 2023-11-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
