# Generated by Django 4.2.7 on 2023-11-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_name'),
        ('license', '0002_alter_license_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
