# Generated by Django 4.2.7 on 2023-11-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_name'),
        ('license', '0003_alter_license_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('license_type', 'person')},
        ),
    ]
