# Generated by Django 4.2.7 on 2023-11-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.IntegerField(unique=True),
        ),
    ]
